# Generated by Django 4.1.4 on 2022-12-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                ("cliente", models.CharField(max_length=150)),
                ("orcamento_id", models.AutoField(primary_key=True, serialize=False)),
                ("servico", models.CharField(max_length=150)),
                ("material", models.CharField(max_length=150)),
                ("quantidade", models.IntegerField()),
                ("valor_do_orcamento", models.FloatField()),
            ],
        ),
    ]
